# GitHub Action for generating a contribution graph with a snake animation.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # setiap 6 jam
  workflow_dispatch:  # memungkinkan eksekusi manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Duwianjar
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: snake-svg
          path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
